package orlov641p.khai.edu.com.controller.lab6idl;
/**
* ServerIDLPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerIDL.idl
* Monday, February 12, 2024 5:26:30 PM EET
*/

public abstract class ServerIDLPOA extends org.omg.PortableServer.Servant
 implements ServerIDLOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sendClientMessage", new java.lang.Integer (0));
    _methods.put ("sendOrderMessage", new java.lang.Integer (1));
    _methods.put ("sendFlightMessage", new java.lang.Integer (2));
    _methods.put ("sendTicketMessage", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ServerIDL/sendClientMessage
       {
         String operation = in.read_string ();
         String $result = null;
         $result = this.sendClientMessage (operation);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ServerIDL/sendOrderMessage
       {
         String operation = in.read_string ();
         String $result = null;
         $result = this.sendOrderMessage (operation);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ServerIDL/sendFlightMessage
       {
         String operation = in.read_string ();
         String $result = null;
         $result = this.sendFlightMessage (operation);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ServerIDL/sendTicketMessage
       {
         String operation = in.read_string ();
         String $result = null;
         $result = this.sendTicketMessage (operation);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ServerIDL/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerIDL:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerIDL _this() 
  {
    return ServerIDLHelper.narrow(
    super._this_object());
  }

  public ServerIDL _this(org.omg.CORBA.ORB orb) 
  {
    return ServerIDLHelper.narrow(
    super._this_object(orb));
  }


} // class ServerIDLPOA
