package orlov641p.khai.edu.com.controller.lab6idl;
/**
* ServerIDLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerIDL.idl
* Monday, February 12, 2024 5:26:30 PM EET
*/

public final class ServerIDLHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerIDL value = null;

  public ServerIDLHolder ()
  {
  }

  public ServerIDLHolder (ServerIDL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerIDLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerIDLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerIDLHelper.type ();
  }

}
