package orlov641p.khai.edu.com.controller.lab6idl;
/**
* ServerIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerIDL.idl
* Monday, February 12, 2024 5:26:30 PM EET
*/

public interface ServerIDL extends ServerIDLOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerIDL
