package orlov641p.khai.edu.com.controller.lab6idl;
/**
* ServerIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerIDL.idl
* Monday, February 12, 2024 5:26:30 PM EET
*/

public interface ServerIDLOperations 
{
  String sendClientMessage (String operation);
  String sendOrderMessage (String operation);
  String sendFlightMessage (String operation);
  String sendTicketMessage (String operation);
  void shutdown ();
} // interface ServerIDLOperations
